version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
#    depends_on:
#      - wordpress
#    environment:
#    secrets:
#    volumes:
    ports:
      - "80:80"
#    networks:
#      - inception_network
    restart: always

#  wordpress:
#    build:
#      context: /requirements/wordpress
#      dockerfile: Dockerfile
#    container_name: wordpress
#    depends_on:
#      - mariadb
#    environment:
#    volumes:
#      - website
#      - database
#    secrets:
#    networks:
#      - inception_network
#    restart: always

  mariadb:
    build:
      context: /requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
#    depends_on:
#    environment:
#    volumes:
#      -database
#    secrets:
#    networks:
#      - inception_network
#    restart: always

#volumes:
#  website:
#    driver: local
#    driver_opts:
#      type: none
#      device: /hom/${USER}/data
#      o: bind

#  database:
#    driver: locar
#    driver_opts:
#      tyoe: none
#      device: /home/${USER}/data

#networks:
#  inception_network:
#    driver: bridge
#secrets: 
